# Generated by Django 4.2 on 2026-01-17 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_catalog_catalogitem_catalogitemtranslation_and_more'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('INSPECTION', 'Inspection'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='LEAD', max_length=30)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.property')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description_override', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='projects.project')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_scope_items', to='core.catalogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_client', models.BooleanField(default=True)),
                ('public_note', models.TextField(blank=True, default='')),
                ('milestone_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_milestones', to='core.catalogitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterialEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_estimates', to='core.catalogitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_estimates', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.CharField(max_length=50)),
                ('hourly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_rates', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('language', models.CharField(default='en', max_length=5)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SIGNED', 'Signed')], default='DRAFT', max_length=20)),
                ('signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='projects.estimate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='projects_pr_company_48dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'project_number'], name='projects_pr_company_6b1e6c_idx'),
        ),
    ]
