# Generated by Django 4.2 on 2026-01-17 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.catalogitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogitemtranslation',
            index=models.Index(fields=['item', 'language'], name='core_catalo_item_id_f597b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogitemtranslation',
            constraint=models.UniqueConstraint(fields=('item', 'language'), name='uq_catalog_item_translation_item_lang'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['catalog', 'sort_order'], name='core_catalo_catalog_e935a5_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['catalog', 'code'], name='core_catalo_catalog_ddbd19_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('catalog', 'code'), name='uq_catalog_item_catalog_code'),
        ),
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_catalog_company_code'),
        ),
    ]
