# Generated by Django 4.2 on 2026-01-17 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_catalog_catalogitem_catalogitemtranslation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('PERMIT', 'Permit'), ('INSPECTION', 'Inspection'), ('PHOTO', 'Photo'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('file_blob', models.BinaryField()),
                ('visible_to_client', models.BooleanField(default=False)),
                ('storage_type', models.CharField(default='DB', max_length=20)),
                ('storage_key', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'project'], name='documents_d_company_6fe407_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'category'], name='documents_d_company_501eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'visible_to_client'], name='documents_d_company_ae69bf_idx'),
        ),
    ]
