# Generated by Django 4.2 on 2026-01-17 01:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(choices=[('HOMEOWNER', 'Homeowner'), ('HOA', 'HOA'), ('PROPERTY_MANAGER', 'Property Manager')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(choices=[('SINGLE_FAMILY', 'Single family'), ('MULTI_FAMILY', 'Multi-family')], default='SINGLE_FAMILY', max_length=30)),
                ('units_count', models.PositiveIntegerField(default=1)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='CA', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['company', 'city'], name='customers_p_company_f5c901_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['company', 'state'], name='customers_p_company_acd63b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['company', 'zip_code'], name='customers_p_company_fb025f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'customer_type'], name='customers_c_company_4b284c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'name'], name='customers_c_company_10527e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'name'], name='customers_c_company_1b1b86_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'is_primary'], name='customers_c_company_6e13b5_idx'),
        ),
    ]
